# Dockerfile.test
# Use an official Node.js runtime as a parent image
FROM node:20

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./


RUN npm install

RUN npm install -g prettier

# Copy the rest of the application files
COPY . .


EXPOSE 3000  
 


CMD [ "npm", "start" ]
