name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Install Docker Compose
      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      # 3. Set up Docker Compose
      - name: Set up Docker Compose
        run: docker-compose -f docker-compose.test.yml up --build -d

      # 4. Run lint and format inside the Docker container
      - name: Run lint and format inside Docker
        run: docker-compose -f docker-compose.test.yml exec muuve_nestjs_api_test npm run lint && npm run format

      # 5. Run unit tests inside Docker
      - name: Run tests inside Docker
        run: docker-compose -f docker-compose.test.yml exec muuve_nestjs_api_test npm run test:unit

      # 6. Tear down Docker containers
      - name: Tear down Docker containers
        run: docker-compose -f docker-compose.test.yml down
