name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker-compose -f docker-compose.test.yml up --build -d

      - name: Run lint and format inside Docker
        run: docker-compose -f docker-compose.test.yml exec muuve_nestjs_api_test npm run lint && npm run format

      - name: Run tests inside Docker
        run: docker-compose -f docker-compose.test.yml exec muuve_nestjs_api_test npm run test:unit

      - name: Tear down Docker containers
        run: docker-compose -f docker-compose.test.yml down
