name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker container
        run: docker build -t my-app .

      - name: Run lint and format inside Docker
        run: docker run my-app npm run lint && npm run format

      - name: Run tests inside Docker
        run: docker run my-app npm run test:unit
